collections_config:
  posts:
    schemas:
      default:
        path: _schemas/post.md
  docs:
    schemas:
      default:
        path: _schemas/docs.md

_inputs:
  types:
    - minor
    - major
  category:
    - contact-syncing
    - devices
    - media