collections_config:
  posts:
    schemas:
      default:
        path: _schemas/post.md
  docs:
    schemas:
      default:
        path: _schemas/docs.md

_inputs:
  types:
    type: select
    options:
      values:
        - minor
        - major
  category:
    type: select
    options:
      values:
        - Contact Syncing
        - Devices
        - Media